# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’

target ‘Kanotguiden-2’ do
    pod 'AFNetworking'
    pod ‘TDOAuth’, ‘~> 1.1’
    pod 'SDWebImage', '~>3.7'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'GoogleMaps'
end

